application: Hello World Vane
version: 1
deploy: true
pub: true
dart2js: true 

handlers:
- url: /hello
  handler: hello_world.dart:HelloWorld

# Static content, will be served by your app's Nginx instance 
- url: /
  match: postregex
  static_dir: web


# Equivalent longer config for the Dart handler above  
#- url: /hello
#  script: hello_world.dart
#  handler: HelloWorld

