application: Hello World Vane
version: 1
deploy: true
pub: true
dart2js: false 

handlers:
- url: /hello
  match: exact 
  script: hello_world.dart
  controller: HelloWorld

# Static content  
- url: /
  match: postregex
  static_dir: web


