name: Vane-Hello-World
framework: vane

handlers:
# Hello backend service using the shorthand syntax
- url: /hello
  match: regex
  handler: hello_world.dart:HelloWorld

# Equivalent alternative to the above config  
#- url: /hello
#  match: regex
#  script: hello_world.dart
#  handler: HelloWorld

# Static content served by Nginx
- url: /
  match: postregex
  static_dir: web


